import type { IRsvRmTasks } from './rsv_rm_tasks.interface';
import type { IRsvRooms } from './rsv_rooms.interface';
import type { IRsvRmGuest } from './rsv_rm_guests.interface';
import type { IRsvRmTariff } from './rsv_rm_tariff.interface';
import type { IRsvRmTariffRates } from './rsv_rm_tariff_rates.interface';
import type { IRsvRmTariffInclusions } from './rsv_rm_tariff_inclusions.interface';
import type { IRsvRmSplitDetails } from './rsv_rm_split_details.interface';
/**
 * Reservation Model
 * Database table: reservation
 * Auto-generated from Python SQLAlchemy model
 * 
 * Note: Default values are handled by backend/database.
 * TypeScript interfaces only describe the data structure.
 */
export interface IReservation {
  id?: number;  // Primary key - auto-generated
  hotelid?: number;
  regnumber?: string;
  foliono?: string;
  rsvtype?: string;
  rsvdate?: Date;
  groupid?: number;
  groupname?: string;
  groupownerid?: number;
  agentid?: number;
  corpid?: number;
  businesssrcid?: number;
  salespersonid?: number;
  purpose?: string;
  preferences?: string;
  checkindate?: Date;
  checkintime?: string;
  checkoutdate?: Date;
  checkouttime?: string;
  checkindatetime?: Date;
  checkoutdatetime?: Date;
  dayusechkindttime?: Date;
  dayusechkoutdttime?: Date;
  duration?: number;
  arrivalmodeid?: number;
  arrivaldetails?: string;
  arrivaltime?: string;
  arrivaltimeshift?: string;
  departuremode?: number;
  departuredetials?: string;
  departuretime?: string;
  departuretimeshift?: string;
  ispaidbyowner?: number;
  ispaidbyguest?: number;
  ownertype?: string;
  rsvstatus?: string;
  counterid?: number;
  webrefid?: string;
  gdstype?: string;
  isnoshow?: number;
  isearlycheckout?: number;
  islatecheckout?: number;
  canceledon?: Date;
  ischanged?: number;
  releasedate?: Date;
  isblocked?: number;
  taxexmptreason?: number;
  taxexmptreasondesc?: string;
  cnclnadate?: Date;
  isbookingfoliogen?: number;
  isratediscpre?: number;
  ispaidfromweb?: number;
  isarrivalassign?: number;
  isdepassign?: number;
  guesttypeid?: number;
  rsvgrouponwertype?: number;
  isoverbooked?: number;
  temprsvid?: number;
  othcurrid?: number;
  conversionrate?: number;
  viewothcurr?: string;
  originalroomdetailsxml?: string;
  cancservcdate?: Date;
  ownerdetailsxml?: string;
  marketsegmentid?: number;
  originalholdtill?: number;
  ishouseuse?: number;
  isdayuse?: number;
  resguestrph?: number;
  checkinrefno?: string;
  locktime?: string;
  createddate?: Date;
  createdon?: Date;  // Auto-populated timestamp
  modifiedon?: Date;  // Auto-populated timestamp
  createdby?: string;  // User ID reference
  modifiedby?: string;  // User ID reference
  task?: IRsvRmTasks;
  rooms?: IRsvRooms;
  guests?: IRsvRmGuest;
  tariffs?: IRsvRmTariff;
  rmtariffs?: IRsvRmTariffRates;
  rmtariffsInclusions?: IRsvRmTariffInclusions;
  rsvSplitDetail?: IRsvRmSplitDetails;
}

export interface ICreateReservation {
  hotelid?: number;
  regnumber?: string;
  foliono?: string;
  rsvtype?: string;
  rsvdate?: Date;
  groupid?: number;
  groupname?: string;
  groupownerid?: number;
  agentid?: number;
  corpid?: number;
  businesssrcid?: number;
  salespersonid?: number;
  purpose?: string;
  preferences?: string;
  checkindate?: Date;
  checkintime?: string;
  checkoutdate?: Date;
  checkouttime?: string;
  checkindatetime?: Date;
  checkoutdatetime?: Date;
  dayusechkindttime?: Date;
  dayusechkoutdttime?: Date;
  duration?: number;
  arrivalmodeid?: number;
  arrivaldetails?: string;
  arrivaltime?: string;
  arrivaltimeshift?: string;
  departuremode?: number;
  departuredetials?: string;
  departuretime?: string;
  departuretimeshift?: string;
  ispaidbyowner?: number;
  ispaidbyguest?: number;
  ownertype?: string;
  rsvstatus?: string;
  counterid?: number;
  webrefid?: string;
  gdstype?: string;
  isnoshow?: number;
  isearlycheckout?: number;
  islatecheckout?: number;
  canceledon?: Date;
  ischanged?: number;
  releasedate?: Date;
  isblocked?: number;
  taxexmptreason?: number;
  taxexmptreasondesc?: string;
  cnclnadate?: Date;
  isbookingfoliogen?: number;
  isratediscpre?: number;
  ispaidfromweb?: number;
  isarrivalassign?: number;
  isdepassign?: number;
  guesttypeid?: number;
  rsvgrouponwertype?: number;
  isoverbooked?: number;
  temprsvid?: number;
  othcurrid?: number;
  conversionrate?: number;
  viewothcurr?: string;
  originalroomdetailsxml?: string;
  cancservcdate?: Date;
  ownerdetailsxml?: string;
  marketsegmentid?: number;
  originalholdtill?: number;
  ishouseuse?: number;
  isdayuse?: number;
  resguestrph?: number;
  checkinrefno?: string;
  locktime?: string;
  createddate?: Date;
  createdby?: string;
  modifiedby?: string;
  task?: IRsvRmTasks;
  rooms?: IRsvRooms;
  guests?: IRsvRmGuest;
  tariffs?: IRsvRmTariff;
  rmtariffs?: IRsvRmTariffRates;
  rmtariffsInclusions?: IRsvRmTariffInclusions;
  rsvSplitDetail?: IRsvRmSplitDetails;
}
export interface IUpdateReservation {
  hotelid?: number;
  regnumber?: string;
  foliono?: string;
  rsvtype?: string;
  rsvdate?: Date;
  groupid?: number;
  groupname?: string;
  groupownerid?: number;
  agentid?: number;
  corpid?: number;
  businesssrcid?: number;
  salespersonid?: number;
  purpose?: string;
  preferences?: string;
  checkindate?: Date;
  checkintime?: string;
  checkoutdate?: Date;
  checkouttime?: string;
  checkindatetime?: Date;
  checkoutdatetime?: Date;
  dayusechkindttime?: Date;
  dayusechkoutdttime?: Date;
  duration?: number;
  arrivalmodeid?: number;
  arrivaldetails?: string;
  arrivaltime?: string;
  arrivaltimeshift?: string;
  departuremode?: number;
  departuredetials?: string;
  departuretime?: string;
  departuretimeshift?: string;
  ispaidbyowner?: number;
  ispaidbyguest?: number;
  ownertype?: string;
  rsvstatus?: string;
  counterid?: number;
  webrefid?: string;
  gdstype?: string;
  isnoshow?: number;
  isearlycheckout?: number;
  islatecheckout?: number;
  canceledon?: Date;
  ischanged?: number;
  releasedate?: Date;
  isblocked?: number;
  taxexmptreason?: number;
  taxexmptreasondesc?: string;
  cnclnadate?: Date;
  isbookingfoliogen?: number;
  isratediscpre?: number;
  ispaidfromweb?: number;
  isarrivalassign?: number;
  isdepassign?: number;
  guesttypeid?: number;
  rsvgrouponwertype?: number;
  isoverbooked?: number;
  temprsvid?: number;
  othcurrid?: number;
  conversionrate?: number;
  viewothcurr?: string;
  originalroomdetailsxml?: string;
  cancservcdate?: Date;
  ownerdetailsxml?: string;
  marketsegmentid?: number;
  originalholdtill?: number;
  ishouseuse?: number;
  isdayuse?: number;
  resguestrph?: number;
  checkinrefno?: string;
  locktime?: string;
  createddate?: Date;
  createdby?: string;
  modifiedby?: string;
  task?: IRsvRmTasks;
  rooms?: IRsvRooms;
  guests?: IRsvRmGuest;
  tariffs?: IRsvRmTariff;
  rmtariffs?: IRsvRmTariffRates;
  rmtariffsInclusions?: IRsvRmTariffInclusions;
  rsvSplitDetail?: IRsvRmSplitDetails;
}